### ISSUE TITLE
Remove warning

### ISSUE THREAD

**Issue by matryer** [stretchr/sdk-cocoa#7]
Class JSONAPI is implemented in both /Users/matryer/Library/Developer/Xcode/DerivedData/Stretchr-bnhqemnwiilcyuejionmckehqpej/Build/Products/Debug/Stretchr.framework/Versions/A/Stretchr and /Users/matryer/Library/Developer/Xcode/DerivedData/Stretchr-bnhqemnwiilcyuejionmckehqpej/Build/Products/Debug/StretchrTests.xctest/Contents/MacOS/StretchrTests. One of the two will be used. Which one is undefined.

**Comment by matryer** [comment]
- in XP, you remove ALL warnings ASAP and don't let them build up.

**Comment by tylerstillwater** [comment]
Where do you get this warning?

**Comment by matryer** [comment]
When I build in the console

**Comment by tylerstillwater** [comment]
It's only because of the tests. Not something to worry about. The pod installation only uses our raw files.
