### ISSUE TITLE
Add some sugar

### ISSUE THREAD

**Issue by tylerstillwater** [stretchr/sdk-cocoa#8]
We need to make the SDK easier to use for common operations. Currently it takes a lot of intermediate steps to perform a simple action.

**Comment by matryer** [comment]
Let's pair up soon and nail this :)

**Comment by tylerstillwater** [comment]
Already working on it.

**Comment by matryer** [comment]
ok mate

**Comment by tylerstillwater** [comment]
Yes let's pair on it. I didn't get anywhere today due to various other things getting in the way.

On January 27, 2014 at 3:19:29 PM, Mat Ryer (notifications@github.com) wrote:

ok mate

**Comment by tylerstillwater** [comment]
@matryer this is another one that really needs attention soon.
